// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlarmUIClient is the client API for AlarmUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlarmUIClient interface {
	// ListEngineSpecs returns a list of Alarm Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (AlarmUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type alarmUIClient struct {
	cc grpc.ClientConnInterface
}

func NewAlarmUIClient(cc grpc.ClientConnInterface) AlarmUIClient {
	return &alarmUIClient{cc}
}

func (c *alarmUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (AlarmUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AlarmUI_ServiceDesc.Streams[0], "/v1.AlarmUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &alarmUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AlarmUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type alarmUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *alarmUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *alarmUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.AlarmUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlarmUIServer is the server API for AlarmUI service.
// All implementations must embed UnimplementedAlarmUIServer
// for forward compatibility
type AlarmUIServer interface {
	// ListEngineSpecs returns a list of Alarm Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, AlarmUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedAlarmUIServer()
}

// UnimplementedAlarmUIServer must be embedded to have forward compatible implementations.
type UnimplementedAlarmUIServer struct {
}

func (UnimplementedAlarmUIServer) ListEngineSpecs(*ListEngineSpecsRequest, AlarmUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedAlarmUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedAlarmUIServer) mustEmbedUnimplementedAlarmUIServer() {}

// UnsafeAlarmUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlarmUIServer will
// result in compilation errors.
type UnsafeAlarmUIServer interface {
	mustEmbedUnimplementedAlarmUIServer()
}

func RegisterAlarmUIServer(s grpc.ServiceRegistrar, srv AlarmUIServer) {
	s.RegisterService(&AlarmUI_ServiceDesc, srv)
}

func _AlarmUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AlarmUIServer).ListEngineSpecs(m, &alarmUIListEngineSpecsServer{stream})
}

type AlarmUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type alarmUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *alarmUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AlarmUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AlarmUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlarmUI_ServiceDesc is the grpc.ServiceDesc for AlarmUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlarmUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AlarmUI",
	HandlerType: (*AlarmUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _AlarmUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _AlarmUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "alarm-ui.proto",
}
